### ISSUE TITLE
When ONLINE show ONLINE MAP

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#1060]
Currently this shows an offline map when online - Please revert to standard behaviour

**Comment by pA1nD** [comment]
This is also described in #937

**Comment by Danman7** [comment]
I'm putting this in all related issues:

After discussion with Stacy, showing her all the map usecases and current scenarios, we descided that the maps' functionality will remain as it is at the moment. There was an issue with wrong coordinates for one of the survey centers which was addding confusion and was fixed in the backend. I'm removing this issue from any sprints and putting it in the icebox, to bedescided if it's going to be worked on.

**Comment by Danman7** [comment]
Closing after inactivity and above comment.
