### ISSUE TITLE
In mentor app it should open the camera, save multiple pictures and send to backend

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#1160]
In mentor app it should open the camera, save multiple pictures and send to backend

**Comment by zommerberg** [comment]
I did some research and the best way we can implement camera is via react-native-camera
https://github.com/react-native-community/react-native-camera

Approach
When clicking the "continue" button at some point on the survey i suppose we will open the camera and then give the ability to take a picture. The question is in how we can send it to the backend. And here it gets tricky.
When we take the picture it will be saved somewhere on the app  and when we send it we could use 
```
var data = new FormData();
data.append('my_photo', {
  uri: filePath, // your file path string
  name: 'my_photo.jpg',
  type: 'image/jpg'
}
```
and then we make the request using 

```
fetch(path, {
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'multipart/form-data'
  },
  method: 'POST',
  body: data
});
```


Notes
- The above explains how to implement the taking of the picture and how to send it to the backend. We still need to knew at what point in the survey this happens.
- There may be problem during the implementation of the react-native-camera because we are using an older version of react native and it requires changes in the android files.

**Comment by aprojas** [comment]
Thank you @zommerberg !
What do we need to update the version of react native? And how long will it take?
If the camera will cause problems because of this, we should definitely update it.

**Comment by zommerberg** [comment]
It is not necessary to update the react version, it might still work with the current one. If we were to update react up to 0.60 and above it would take weeks, because of the connected libraries and the android files tightly working with the 0.59 version of react.
