### ISSUE TITLE
Error while trying to sync invalid snapshot

### ISSUE THREAD

**Issue by loorely** [FundacionParaguaya/MentorApp#1167]
## General Description 

<img width="354" alt="syn-error-2" src="https://user-images.githubusercontent.com/740232/73488340-86d56780-4387-11ea-917f-b4b5a87ec00a.png">
<img width="372" alt="sync-error" src="https://user-images.githubusercontent.com/740232/73488341-86d56780-4387-11ea-9717-803cc635c148.png">

**Comment by zommerberg** [comment]
In this issue we would like to fix the clicking on the sync error resulting to app error.
Clicking on the error should navigate us to the overview screen but it crashes instead

Problem 
I was able to reproduce the problem and found a possible reason for it. 
Because we are able to click on the sync error and go to the overview screen directly from the dasboard without any problems. But we cant do this from the Sync screen the reason why this is happening is because we are passing incomplete/different props to the sync error component in the sync screen

Solution
We need to check and compare the props we are sending from the dashboard to the props we are sending on the Sync screen. One of them is probably either missing or undefined. It is also possible that we are sending incorrect props
