### ISSUE TITLE
'Email address' should not be mandatory question in UK survey

### ISSUE THREAD

**Issue by pepamc** [FundacionParaguaya/MentorApp#179]
In the old platform, the "email address" question in the socioeconomic survey was not a mandatory question that had to be answered before responding. Now it is but it should not be.

**Comment by stacylorraineprendeville** [comment]
I am reporting this as a BUG - This should not be a mandatory element - 
This issue is NOT appearing in the WARC survey.
@diegotorrespy @IvaKop This has been reported twice now as an issue  - I cannot reproduce it - Can you look into this for the UK survey
@pepamc can you confirm the survey you are testing on---this is NOT a global issue.

**Comment by stacylorraineprendeville** [comment]
Potentially this is not an issue and the client is confused between seeing the field and it being mandatory @pepamc please review

**Comment by stacylorraineprendeville** [comment]
this appears to be mis-communication. The client did not state this appeared as mandatory - they stated they saw this on the page.
