### ISSUE TITLE
When logging out and logging back in survey images disappear

### ISSUE THREAD

**Issue by IvaKop** [FundacionParaguaya/MentorApp#205]
**Describe the bug**
When I log in as a user, then I log out, then I login as a different user, create a draft and go to the questions screen, I no longer see images.

When I logout and then I login back in as the same user - I no longer see the images - The images ONLY appear on emptying the data and the cache

**Expected behavior**
I should still see images

**Smartphone (please complete the following information):**
 - Device: Emulator
 - OS: Android Oreo

**Comment by Danman7** [comment]
After yesterday's update I can no longer reproduce this at all, on any of the 6 surveys available to demo account. Here are my previous findings in case this appears again.

The missing images themselves do appear after a few minutes of waiting on the question page. Sometimes they appear for a second, disappear and reappear again.

I've ruled out any connection between this issue and #242 - all images sync when this issue was reproducible. I also don't see size being an issue as all images amount to around 90MB, where we were had no problems when images were 300MB of disk space.

My guess is that react-native again does some optimisation under the hood when ram is low.

If you reproduce this, please let me know the name of the survey you use.

**Comment by IvaKop** [comment]
@Danman7 @stacylorraineprendeville I tested this and cannot reproduce the disappearing of images either. However, another bug appears. Once I logout and login again the slider in the question screen does not position itself correctly anymore. When you slide, it does not go into the correct position on the yellow image.

**Comment by stacylorraineprendeville** [comment]
@IvaKop Will you then close this if cannot be reproduced and create an issue for the new bug you found?
