### ISSUE TITLE
Continue button and validation

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#232]
In order to save production time for the december deadline various adjustments were made to the flow of form validation. This issue is to return to the initial idea of the validation during the lifemap process, improving usability. In the initial flow the continue button should always be activated.

1. The continue button is always active
2. As currently - Validation is added to the fields during form completion
3. We add in this issue that when a user clicks on the continue button - All mandatory fields are marked error red and noted that "This field is required" and any fields with incorrectly inputted text continue to display the error message of the error.

This improves usability by easily showing the user the required fields before advancement - The current disabling method is difficult to understand.

The following illustration demonstrates the situation when a user clicks continue without adding 2 required fields.

![Screen Shot 2018-12-27 at 12.22.14.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/7f2266ef-5a62-49e6-8299-5e5329686188)

**Comment by Danman7** [comment]
@stacylorraineprendeville The validation system involves several components and I need to be sure that I understand this correctly before estimating:
- When editing a field it's validation state (showing errors) doesn't change?
- You only see the errors the first time you press Continue?
- What happens if you correctly enter a field after an error is show - we hide the error only after pressing Continue?

**Comment by Danman7** [comment]
This makes it clear. I'm integrating this into the Achievements changes and thus will change my estimate.

**Comment by Danman7** [comment]
Merged
