### ISSUE TITLE
Map - try to get GPS coordinates even if user is offline

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#250]
Currently when the user is offline we hide the map and show a message. We however don't set any coordinates to the draft. We should still try to look for GPS coordinates even offline.

**Comment by stacylorraineprendeville** [comment]
INTERNET: YES
1. Internet : Yes, GPS : On and With locatino
Position Map pin on corect position in the Map - IMPLEMENTED

2. Internet : yes, GPS : Off
Turn on GPS message & reload GPS.
If GPS works -> Position map pin on correct position in map - IMPLEMENTED

3. Internet : yes, GPS : On but No location
Display map with global view and request user to position pin on map - IMPLEMENTED - MAP IS CENTRED ON THE SURVEY LOCATION


----
INTERNET : NO

4. Internet : no, GPS : Off
Give a message like the following.
Unfortunately, we cannot load the map because you are offline.  - AS PER USE CASE 2 - SAME ERROR MESSAGE

5. Internet : No, GPS : On and with location
Give a message like the following: - TO IMPLEMENT - DAN HAS IMAGE
Unfortunately we cannot load the map because you are offline. However we were able to get your device location accurate to [value] meters. Do you want to reload to get a more accurate location <Button>```

```6. Internet: No, GPS : On but no location
Give a message like the following:
Unfortunately we cannot load the map nor can we get your device location. Could you describe your location as accurate as possible below?
