### ISSUE TITLE
Remove the mandatory required on Family Member Names

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#380]
If we remove the requirement for family member names as mandatory - A user is more likely to tell us how many people live in the family.

This issue is to remove the family member names as mandatory.

An open question is whether this means we will need to autofill? Member 1 Member 2 etc.
Also if a user provides no family member names - It would be impossible to add genders and birth dates - How would we detect this and not show this screen?

**Comment by IvaKop** [comment]
@stacylorraineprendeville I can't estimate this until we answer these questions. Also this will require a change in the server if we do not use a placeholder since currently the first name for each family member is mandatory in there as well. Using Member 1, 2 raises a translation issue (what if the survey is in Spanish?). This should also be discussed with the backend to see what they think.
