### ISSUE TITLE
Number of indicators in title

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#391]
For every survey, when in the Life Map section, next to every indicator title should be the number of that indicator in order to identify them easily. And to know in which number you are when taking the survey. This should also be replicated on the platform.

**Comment by stacylorraineprendeville** [comment]
This is removed Ana - I spoke with Replicas and we agreed that the progress bar will cover all pages in the future (including families list etc)
the numbers therefore will not make sense and were removed. 
This is because we need to think about the survey Globally - The numbers are NOT useful to users - They cannot identify ANYTHING with that number
