### ISSUE TITLE
Automatic Answer to the Income stoplight indicator based on socio economic income questions answer

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/MentorApp#430]

**Comment by Danman7** [comment]
@stacylorraineprendeville Which fields is this related to? Can you give me an example survey and question text so I can check?

**Comment by Danman7** [comment]
I still need info on this.

**Comment by stacylorraineprendeville** [comment]
@Danman7 This is on hold

**Comment by stacylorraineprendeville** [comment]
-Comments from Nancy-
Estos son criterios: 

Primero: 

Zona (por ejemplo urbana y rural), cada país tienen distintos números de zonas (por ejemplo Colombia tienen tres)

De acuerdo a la zona tenemos que establecer la linea de pobreza para cada nivel (por ejemplo para la zona urbana nivel verde mayo a 200, para la zona urbana nivel amarilla es entre 200 - 100, para la zona urbana nivel rojo es menos de 100. 

Segundo: 
-       Ingreso del encuestado + ingreso de otros miembros / cantidad de miembros = ingreso percapita

Tercero: 
Según la linea de pobreza que le corresponde se identifica el nivel de pobreza.

**Comment by aprojas** [comment]
This is the latest update: @stacylorraineprendeville 

Use case Indicador ingresos:

A) Depending if the person chooses a "Zona", the Income amount changes. These are the dropdown options of "ZONA":
- Cabeceras
- Centros poblados y rural disperso
- 13 ciudades y areas metropolitanas

B)	
![sdfsdf.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/f96488c5-135f-4bb6-9854-0b801dfd1239)

C) To calculate:
The sum up of the following fields:
1. Ingreso mensual
2. Monto de ingresos que generan otros miembros
3. Monto Recibido por el gobierno

And then, DIVIDE them by the number of family members:

Example:
Ana Paula lives in the area "Cabeceras". 
-	(field 1) Ingreso mensual: 100.000
-	(field 2) Monto de otros miembros: 100.000
-	(field 3) Monto Recibido por gobierno: 100.000
Total: 300.000
Since Anapaula has another member, they are 2 family members. 

Then the formula is 300.000 / 2 = 150.000
Ana Paula's household belong to the range of the yellow level in the income indicator. 
And that indicator should be automatically selected.

**Comment by stacylorraineprendeville** [comment]
WONT DO
