### ISSUE TITLE
Add more height at the top of the page

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#603]
More height at the top of the page when we have the text and the balls image background.
Give the form elements more breathing space at the top  - refer back to the invision files.

this is in the family profile page:
![Screenshot_2019-05-07-10-00-11.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/55331392-71c1-4b36-8f22-95a6e19b8243)

This is the main board
![Screenshot_2019-05-07-10-03-15.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/50702f75-ba2f-4409-b6d9-cfcb8854320a)

**Comment by Danman7** [comment]
@stacylorraineprendeville I would like us to have some sort of design, or at least guide on how much space to give the elements. We all know what happens when developers start to play at design.

**Comment by stacylorraineprendeville** [comment]
@Danman7 When I review the design here I see 120 pixels height between header and content

![Screen Shot 2019-06-13 at 12.27.49.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/881526d2-44aa-40ae-af01-e5a4648de109)

I know we potentially do not use PIxel Perfect in Mobile - when I look at the design above we have a 60 pixel height between header and content - See below
So I am asking for it to be doubled :)

[Uploading... Screen Shot 2019-06-13 at 12.30.15.png ]

**Comment by zommerberg** [comment]
This is how it looks like on phone and tablet right now ,could you check if this is still an issue?
I believe there is no need to change anything, because it might be already fixed.
<img width="269" alt="Screenshot 2019-06-26 at 14 00 28" src="https://user-images.githubusercontent.com/43446836/60175358-07dde680-981c-11e9-99e0-a59324a9eb83.png">
<img width="481" alt="Screenshot 2019-06-26 at 14 08 30" src="https://user-images.githubusercontent.com/43446836/60175361-07dde680-981c-11e9-8da3-c8378be40140.png">
<img width="484" alt="Screenshot 2019-06-26 at 14 09 08" src="https://user-images.githubusercontent.com/43446836/60175363-07dde680-981c-11e9-9243-caad2e5de907.png">

**Comment by stacylorraineprendeville** [comment]
@zommerberg sure this looks good :)
