### ISSUE TITLE
Device memory full - no space for images/maps

### ISSUE THREAD

**Issue by Danman7** [FundacionParaguaya/MentorApp#630]
Related issue: https://sentry.io/share/issue/f13d46a5020942a38db70a515750420a/

At the moment, we don't have any error handling for when the device or it's sd card is out of memory. And this is an app that is caching quite a bit of stuff. The error was experienced in the demo account and that caches over 350mb of data.

We need to find a way to check the device's remaining memory and warn the user before caching starts.

**Comment by Danman7** [comment]
I'm not currently shure how to calculate amount of space on the device. I will need to clarify after a bit of research.

**Comment by vasildimitroffhristoff** [comment]
We were able to check if  the remaining storage space is enough and output an error if the user's device is running out of free space, but we don't have UI for this one, so we are simply outputting error message below the form.

![Screenshot_20190523-160347](https://user-images.githubusercontent.com/47756276/58255038-c8336300-7d74-11e9-8264-9a136b35da57.png)

**Comment by stacylorraineprendeville** [comment]
![Screen Shot 2019-06-14 at 14.45.33.png](https://images.zenhubusercontent.com/5c19ffa9a896da5d83d6a0d0/caf54476-6fc9-47f3-a17d-1f035dc32260)

**Comment by stacylorraineprendeville** [comment]
@aprojas can you give @vasildimitroffhristoff a translation for the above?

**Comment by aprojas** [comment]
**Screenshot 1:**
_English:_ You have only (233 mb) storage space left. Free up space in order to continue.
_Spanish:_ Sólo te quedan (233 mb) de espacio de almacenamiento. Libere espacio para continuar.

**Screenshot 2:** 
_English:_ Hmm... your device memory is full!
_Spanish:_ Hmm.... ¡la memoria de tu dispositivo está llena!

_English:_ Please free up "number mb" of space to continue using Stoplight Mobile.
_Spanish:_ Por favor, libere "número de mb" de espacio para continuar usando Stoplight Mobile.

@vasildimitroffhristoff here it is!
@stacylorraineprendeville just change it if you have any comments!
