### ISSUE TITLE
Type error in Location screen when you don't give permissions to be localized

### ISSUE THREAD

**Issue by vasildimitroffhristoff** [FundacionParaguaya/MentorApp#717]
When you fill your life map and when you don't give  access to your location you get red screen with TypeError :  undefined is not an object (evaluating 'draft.familyData')

**Comment by zommerberg** [comment]
when i click on deny ,the popup witch asks about the location permission appears again and again and again. What behavior should we have when the user denies the permission? Should we show the "Cannot locate" message? @vasildimitroffhristoff  @Danman7  @stacylorraineprendeville

**Comment by stacylorraineprendeville** [comment]
@zommerberg if the user is offline and denies using location we cannot locate them.
What is this persistent pop-up? Becuase I am not aware of it
Can you send through a screen grab?

**Comment by zommerberg** [comment]
I need to know what happens if the user is online and denies using the location.
The popup below is the persistent one.
@stacylorraineprendeville 
<img width="265" alt="Screenshot 2019-07-10 at 12 36 52" src="https://user-images.githubusercontent.com/43446836/60958693-70928c00-a30f-11e9-9ddf-89ac77028714.png">

**Comment by stacylorraineprendeville** [comment]
@zommerberg then we go to the screen "we cannot locate you, use the form below to tell us about your location" - cannot remember exactly the screen but it is this one....
