### ISSUE TITLE
Geco errors

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/MentorApp#825]
On Tuesday 18 of June:

Geco sent me a screenshot with 3 sync errors. 
This error was reported and Geco was told to not log out of his user. 

On June 20, the version 1.9.9 that would solve this problem was launched. 
They were told to update the app WITHOUT logging out of their user. 
That same day, they told me they followed those instructions, but when they opened the app again, the loading screen was there forever. It stayed in the "1 survey synced" and the red circle continued moving. 

Geco said they had 200 unsynced surveys (pending syncs and some sync errors) with that same user. 

Then, Geco gave me the credentials so we could reproduce the error and the error was seen from the Tech team. 

The families timed out with a 502 proxy error from the server
Diego is pushing a fix today (Monday 24 June)

July 2
Geco reported that they still have 100 pending syncs.
They are using the version 1.9.10

July 2 later

1. They have 40 real "pending syncs", it looks like the others that synced never had the "pending sync" label, they were just drafts that they continued until the end. So when they clicked on "save and close", it synced perfectly. BUT, their original "pending syncs" never did sync.
2. It cannot be an internet connection. They did it over night, they also connected the wifi internet to one tablet at a time.
3. They updated the app to 1.9.12, still nothing changed.

July 8 

They updated the app 1.9.13 which would fix this with a "Retry" button. 
They clicked on the families that had pending sync, they clicked on the "Retry" button and nothing happened.

**Comment by Danman7** [comment]
Geco are reporting they have pending syncs which are never showing sync error.

![Imagen de iOS (1)](https://user-images.githubusercontent.com/3336245/60187848-fd7d1600-9836-11e9-8457-e6d9dc967c83.jpg)

![Imagen de iOS](https://user-images.githubusercontent.com/3336245/60187851-ffdf7000-9836-11e9-9f12-24011262fe71.jpg)

**Comment by aprojas** [comment]
I reopened this ticket and updated it in the description @Danman7

**Comment by stacylorraineprendeville** [comment]
@aprojas Can you update this issue ongoing as a status of GECO

**Comment by Danman7** [comment]
@aprojas There has been no communication regarding these issues ever since we released the latest fixes. Can you post an update? Thank you :)

**Comment by stacylorraineprendeville** [comment]
@Danman7 We still want to retrieve these sync errors and pending syncs
The client needed to make a report of all data and could not wait and pass more and more time with us on this - So they reported to the officials the aggregated data without the missing surveys (approximately 50 as he explains) so the issue goes on and we do not close it until we have rectified it.
@aprojas do you know over how many devices the issues is prevalent? 10/20? I ask because if it needs to be it will have to be fedexed over - lets not give up on this




Client contact here - stick it through the google translate if you want ;)
Te cuento que pudimos coordinar una reunión con el Gerente General de Guzmán y Larraín hace unas semanas. Tomando en cuenta que ya había pasado más de un mes y no habíamos tenido solución a este problema y, sin ánimo de seguir retrasando la entrega de resultados, tuvimos que avanzar y entregar lo que teníamos. No pudimos recuperar las 50 encuestas que teníamos perdidas ni las 30 encuestas (aprox) que no se pudieron sincronizar.

En función de no quedarnos parados, decidí avanzar. Perdón por no avisarte antes, pero esa reunión desembocó en tomar acciones frente a los resultados, por lo que han sido días y semanas muy duras.

Te cuento los próximos pasos cuando tenga más claridades de fechas de las siguientes tomas de encuesta bueno?

Un abrazo y gracias por estar pendiente.

**Comment by stacylorraineprendeville** [comment]
@Danman7 this is not closed until we have reclaimed those syncs

**Comment by Danman7** [comment]
Oooops, my bad. I was just cleaning up.
